<?php
/**
 * EYEMAGINE - The leading Magento Solution Partner
 *
 * Layered Nav Limit
 *
 * @author    EYEMAGINE <magento@eyemaginetech.com>
 * @category  Eyemagine
 * @package   Eyemagine_LayeredNavLimit
 * @copyright Copyright (c) 2014 EYEMAGINE Technology, LLC (http://www.eyemaginetech.com)
 * @license   http://www.eyemaginetech.com/license.txt
 */
?>
<?php
/**
 * Template for filter items block
 *
 * @see Eyemagine_LayeredNavLimit_Block_Catalog_Layer_Filter_Attribute
 */
$_limit = $this->getLayeredNavLimitHelper()->getLimit();
?>

<ol>
<?php foreach ($this->getItems() as $_i => $_item): ?>
    <li class="<?php echo $_i < $this->getLayeredNavLimitHelper()->getLimit() ? '' : 'lnl-hidden' ?>">
        <?php if ($_item->getCount() > 0): ?>
        <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
        <?php else: echo $_item->getLabel() ?>
        <?php endif; ?>
        <?php if ($this->shouldDisplayProductCount()): ?>
        (<?php echo $_item->getCount() ?>)
        <?php endif; ?>
    </li>
<?php endforeach ?>
<?php if ($_limit < $this->getItemsCount()): ?>
    <li>
        <a href="#" class="lnl-more"><?php echo $this->__('More...') ?></a>
        <a href="#" class="lnl-less lnl-hidden"><?php echo $this->__('Less...') ?></a>
    </li>
<?php endif ?>
</ol>